---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create ElasticLoadBalancingV2 Resources
Parameters:
  StackName:
    Type: String
  VpcId:
    Description: Name of VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: Choose which PublicSubnets the Applicaion Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  TargetGroupMongo:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-mongo-${StackName}
      TargetType: ip
      VpcId: !Ref VpcId
      Port: 27017
      Protocol: TCP
  ListenerMongo:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupMongo
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 27017
      Protocol: TCP
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub nlb-${StackName}
      Type: network
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
Outputs:
  LoadBalancerDns: 
    Description: A reference to the DNS of the NetworkLoadBalancer
    Value: !GetAtt NetworkLoadBalancer.DNSName
  TargetGroupMongoArn: 
    Description: The ARN of the Mongo Target Group
    Value: !Ref TargetGroupMongo


