---
AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template For Spring Cloud Stream IoT Demo

Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: Choose the PublicSubnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Description: Select the Security Group
    Type: AWS::EC2::SecurityGroup::Id
  FargateClusterName:
    Type: String

Resources:
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/iam.yaml

  TaskDefBackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/task-def-backend.yaml
      Parameters:
        EcsTaskExecutionRoleArn: !GetAtt IamStack.Outputs.EcsTaskExecutionRoleArn
        ScsTaskRoleArn: !GetAtt IamStack.Outputs.ScsTaskRoleArn
        StackName: !Ref AWS::StackName

  NlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/nlb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        StackName: !Ref AWS::StackName

  SvcBackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/svc-backend.yaml
      Parameters:
        TaskDefMongoArn: !GetAtt TaskDefBackendStack.Outputs.DefMongoArn
        TargetGroupMongoArn: !GetAtt NlbStack.Outputs.TargetGroupMongoArn
        FargateClusterArn: 
          !Join
          - ":"
          - - "arn"
            - "aws"
            - "ecs"
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - !Sub cluster/${FargateClusterName}
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !Ref SecurityGroup






  # EcsStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-iot/ecs-backend-nlb.yaml
  #     Parameters:
  #       TaskDefMongoArn: !GetAtt TaskDefBackendStack.Outputs.DefMongoArn
  #       TaskDefGeodeArn: !GetAtt TaskDefBackendStack.Outputs.DefGeodeArn
  #       TargetGroupMongoArn: !GetAtt NlbStack.Outputs.TargetGroupMongoArn
  #       TargetGroupGeodeArn: !GetAtt NlbStack.Outputs.TargetGroupGeodeArn
  #       EcsClusterArn: "arn:aws:ecs:ap-northeast-1:042083552617:cluster/ec2-scs"

