---
AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template For Spring Cloud Stream IoT Demo

Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: Choose the PublicSubnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Description: Select the Security Group
    Type: AWS::EC2::SecurityGroup::Id
  FargateClusterName:
    Type: String
    Default: fargate
  DestinationPath:
    Type: String
    Default: /glue-output-us-east-1/geojson

Resources:
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/iam.yaml

  NlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/nlb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        StackName: !Ref AWS::StackName

  TaskDefBackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/task-def-backend.yaml
      Parameters:
        EcsTaskExecutionRoleArn: !GetAtt IamStack.Outputs.EcsTaskExecutionRoleArn
        ScsTaskRoleArn: !GetAtt IamStack.Outputs.ScsTaskRoleArn
        StackName: !Ref AWS::StackName
        NlbDns: !GetAtt NlbStack.Outputs.LoadBalancerDns

  TaskDefAppsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/task-def-apps.yaml
      Parameters:
        NlbDns: !GetAtt NlbStack.Outputs.LoadBalancerDns
        EcsTaskExecutionRoleArn: !GetAtt IamStack.Outputs.EcsTaskExecutionRoleArn
        ScsTaskRoleArn: !GetAtt IamStack.Outputs.ScsTaskRoleArn
        StackName: !Ref AWS::StackName
        DestinationPath: !Ref DestinationPath

  SvcBackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/svc-backend.yaml
      Parameters:
        TargetGroupMongoArn: !GetAtt NlbStack.Outputs.TargetGroupMongoArn
        TaskDefMongoArn: !GetAtt TaskDefBackendStack.Outputs.DefMongoArn
        FargateClusterArn: 
          !Join
          - ":"
          - - "arn"
            - "aws"
            - "ecs"
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - !Sub cluster/${FargateClusterName}
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !Ref SecurityGroup

  SvcAppsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SvcBackendStack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/scs-kinesis-handson/for-http-source/svc-apps.yaml
      Parameters:
        TargetGroupHttpArn: !GetAtt NlbStack.Outputs.TargetGroupHttpArn
        TaskDefHttpSourceArn: !GetAtt TaskDefAppsStack.Outputs.DefHttpSourceArn
        TaskDefFilterProcessorLinesArn: !GetAtt TaskDefAppsStack.Outputs.DefFilterProcessorLinesArn
        TaskDefGeocodingProcessorArn: !GetAtt TaskDefAppsStack.Outputs.DefGeocodingProcessorArn
        TaskDefFilterProcessorGeojsonArn: !GetAtt TaskDefAppsStack.Outputs.DefFilterProcessorGeojsonArn
        TaskDefLogSinkArn: !GetAtt TaskDefAppsStack.Outputs.DefLogSinkArn
        TaskDefS3SinkArn: !GetAtt TaskDefAppsStack.Outputs.DefS3SinkArn
        FargateClusterArn: 
          !Join
          - ":"
          - - "arn"
            - "aws"
            - "ecs"
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - !Sub cluster/${FargateClusterName}
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !Ref SecurityGroup

  