---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to Create Fargate Task Definition for Backend

Parameters:
  StackName:
    Type: String
  EcsTaskExecutionRoleArn:
    Type: String
  ScsTaskRoleArn:
    Type: String
  NlbDns:
    Type: String

Resources:
  LogGroupMongo:
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: !Sub /ecs/mongo-geojson-${StackName}

  DefMongo: 
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      Family: !Sub def-mongo-geojson-${StackName}
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn:
        Ref: EcsTaskExecutionRoleArn
      Memory: "2048"
      Cpu: "1024"
      TaskRoleArn:
        Ref: ScsTaskRoleArn
      NetworkMode: "awsvpc"
      ContainerDefinitions: 
        - 
          Name: "mongo-geojson"
          Image: "komushi/mongo-geojson"
          Essential: "true"
          PortMappings:
            -
              ContainerPort: 27017
              HostPort: 27017
              Protocol: "tcp"
          LogConfiguration: 
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Ref LogGroupMongo
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"

  LogGroupFlatFileReader:
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: !Sub /ecs/flat-file-reader-${StackName}

  DefFlatFileReader: 
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      Family: !Sub def-flat-file-reader-${StackName}
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn:
        Ref: EcsTaskExecutionRoleArn
      Memory: "1024"
      Cpu: "512"
      TaskRoleArn:
        Ref: ScsTaskRoleArn
      NetworkMode: "awsvpc"
      ContainerDefinitions: 
        - 
          Name: "flat-file-reader"
          Image: "komushi/flat-file-reader"
          Essential: "true"
          Command: 
            - !Sub "--url=http://${NlbDns}:8000"
          LogConfiguration: 
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Ref LogGroupFlatFileReader
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"

Outputs:
  DefMongoArn:
    Description: ARN of the Mongo task definition
    Value:
      Ref: DefMongo
